name: 'MCP Conformance Test'
description: 'Test MCP server conformance between versions'
author: 'Sam Morrow'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  # Language setup (optional convenience)
  setup_node:
    description: 'Set up Node.js environment'
    required: false
    default: 'false'
  node_version:
    description: 'Node.js version (default: 20)'
    required: false
    default: '20'
  setup_python:
    description: 'Set up Python environment'
    required: false
    default: 'false'
  python_version:
    description: 'Python version (default: 3.11)'
    required: false
    default: '3.11'
  setup_go:
    description: 'Set up Go environment'
    required: false
    default: 'false'
  go_version:
    description: 'Go version (default: read from go.mod)'
    required: false
    default: ''
  setup_rust:
    description: 'Set up Rust environment'
    required: false
    default: 'false'
  rust_toolchain:
    description: 'Rust toolchain (default: stable)'
    required: false
    default: 'stable'
  setup_dotnet:
    description: 'Set up .NET environment'
    required: false
    default: 'false'
  dotnet_version:
    description: '.NET version (default: 8.0.x)'
    required: false
    default: '8.0.x'

  # Build configuration
  install_command:
    description: 'Command to install dependencies (optional if no install step needed)'
    required: false
    default: ''
  build_command:
    description: 'Command to build the MCP server (optional for interpreted languages)'
    required: false
    default: ''
  start_command:
    description: 'Command to start the MCP server (for stdio transport, or to start HTTP server)'
    required: false
    default: ''

  # Transport configuration
  transport:
    description: 'Transport type: stdio or streamable-http'
    required: false
    default: 'stdio'
  server_url:
    description: 'Server URL for HTTP transport (e.g., http://localhost:3000/mcp)'
    required: false
    default: ''
  configurations:
    description: 'JSON array of test configurations for multiple transports. Each object: name, transport, start_command, server_url, env_vars, custom_messages'
    required: false
    default: ''
  custom_messages:
    description: 'JSON array of custom JSON-RPC messages to send. Each object: id (number), name (string), message (JSON-RPC object). Applied to all configurations unless overridden per-config.'
    required: false
    default: ''
  headers:
    description: 'HTTP headers to send with streamable-http requests. JSON object or newline-separated "Header: value" pairs. Applied to all HTTP configurations unless overridden per-config.'
    required: false
    default: ''

  # Test configuration
  compare_ref:
    description: 'Git ref to compare against (auto-detects merge-base or previous tag if not set)'
    required: false
    default: ''
  fail_on_error:
    description: 'Fail the action if probe errors occur (not just API differences)'
    required: false
    default: 'true'
  env_vars:
    description: 'Environment variables (newline-separated KEY=VALUE pairs)'
    required: false
    default: ''
  server_timeout:
    description: 'Timeout in seconds to wait for server response'
    required: false
    default: '10'

outputs:
  status:
    description: 'Test status (passed, differences, or error)'
    value: ${{ steps.conformance.outputs.status }}
  report_path:
    description: 'Path to the conformance report'
    value: 'conformance-report/CONFORMANCE_REPORT.md'

runs:
  using: 'composite'
  steps:
    # Optional language setup
    - name: Set up Node.js
      if: inputs.setup_node == 'true'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node_version }}

    - name: Set up Python
      if: inputs.setup_python == 'true'
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ inputs.python_version }}

    - name: Set up Go
      if: inputs.setup_go == 'true'
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ inputs.go_version || null }}
        go-version-file: ${{ inputs.go_version == '' && 'go.mod' || null }}

    - name: Set up Rust
      if: inputs.setup_rust == 'true'
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
      with:
        toolchain: ${{ inputs.rust_toolchain }}

    - name: Set up .NET
      if: inputs.setup_dotnet == 'true'
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Set environment variables
      if: inputs.env_vars != ''
      shell: bash
      run: |
        echo "${{ inputs.env_vars }}" >> $GITHUB_ENV

    - name: Run conformance test
      id: conformance
      shell: bash
      env:
        INPUT_INSTALL_COMMAND: ${{ inputs.install_command }}
        INPUT_BUILD_COMMAND: ${{ inputs.build_command }}
        INPUT_START_COMMAND: ${{ inputs.start_command }}
        INPUT_SERVER_TIMEOUT: ${{ inputs.server_timeout }}
        INPUT_COMPARE_REF: ${{ inputs.compare_ref }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_TRANSPORT: ${{ inputs.transport }}
        INPUT_SERVER_URL: ${{ inputs.server_url }}
        INPUT_CONFIGURATIONS: ${{ inputs.configurations }}
        INPUT_CUSTOM_MESSAGES: ${{ inputs.custom_messages }}
        INPUT_HEADERS: ${{ inputs.headers }}
        INPUT_ENV_VARS: ${{ inputs.env_vars }}
        INPUT_SETUP_NODE: ${{ inputs.setup_node }}
        INPUT_NODE_VERSION: ${{ inputs.node_version }}
        INPUT_SETUP_PYTHON: ${{ inputs.setup_python }}
        INPUT_PYTHON_VERSION: ${{ inputs.python_version }}
        INPUT_SETUP_GO: ${{ inputs.setup_go }}
        INPUT_GO_VERSION: ${{ inputs.go_version }}
        INPUT_SETUP_RUST: ${{ inputs.setup_rust }}
        INPUT_RUST_TOOLCHAIN: ${{ inputs.rust_toolchain }}
        INPUT_SETUP_DOTNET: ${{ inputs.setup_dotnet }}
        INPUT_DOTNET_VERSION: ${{ inputs.dotnet_version }}
      run: |
        node "${{ github.action_path }}/dist/index.js"

    - name: Generate Job Summary
      shell: bash
      run: |
        echo "# MCP Server Conformance Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -n "${{ inputs.compare_ref }}" ]; then
          echo "Comparing against: \`${{ inputs.compare_ref }}\`" >> $GITHUB_STEP_SUMMARY
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "Comparing tag against previous tag (auto-detected)" >> $GITHUB_STEP_SUMMARY
        else
          echo "Comparing against merge-base with \`origin/main\`" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f conformance-report/CONFORMANCE_REPORT.md ]; then
          tail -n +5 conformance-report/CONFORMANCE_REPORT.md >> $GITHUB_STEP_SUMMARY
        else
          echo "Report file not found - check the workflow logs for errors" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.conformance.outputs.status }}" = "passed" ]; then
          echo "**All conformance tests passed** - No behavioral differences detected." >> $GITHUB_STEP_SUMMARY
        else
          echo "**Differences detected** - Review the diffs above to ensure changes are intentional." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Common expected differences:" >> $GITHUB_STEP_SUMMARY
          echo "- New tools added" >> $GITHUB_STEP_SUMMARY
          echo "- Tool descriptions updated" >> $GITHUB_STEP_SUMMARY
          echo "- New resources or prompts" >> $GITHUB_STEP_SUMMARY
          echo "- Capability changes" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload conformance report
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: conformance-report
        path: conformance-report/
        if-no-files-found: ignore
