name: 'MCP Conformance Test'
description: 'Test MCP server conformance between versions'
author: 'Sam Morrow'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  # Language setup (optional convenience)
  setup_node:
    description: 'Set up Node.js environment'
    required: false
    default: 'false'
  node_version:
    description: 'Node.js version (default: 20)'
    required: false
    default: '20'
  setup_python:
    description: 'Set up Python environment'
    required: false
    default: 'false'
  python_version:
    description: 'Python version (default: 3.11)'
    required: false
    default: '3.11'
  setup_go:
    description: 'Set up Go environment'
    required: false
    default: 'false'
  go_version:
    description: 'Go version (default: read from go.mod)'
    required: false
    default: ''
  setup_rust:
    description: 'Set up Rust environment'
    required: false
    default: 'false'
  rust_toolchain:
    description: 'Rust toolchain (default: stable)'
    required: false
    default: 'stable'
  setup_dotnet:
    description: 'Set up .NET environment'
    required: false
    default: 'false'
  dotnet_version:
    description: '.NET version (default: 8.0.x)'
    required: false
    default: '8.0.x'

  # Build configuration
  install_command:
    description: 'Command to install dependencies (optional if no install step needed)'
    required: false
    default: ''
  build_command:
    description: 'Command to build the MCP server (optional for interpreted languages)'
    required: false
    default: ''
  start_command:
    description: 'Command to start the MCP server (for stdio transport, or to start HTTP server)'
    required: false
    default: ''

  # Transport configuration
  transport:
    description: 'Transport type: stdio or streamable-http'
    required: false
    default: 'stdio'
  server_url:
    description: 'Server URL for HTTP transport (e.g., http://localhost:3000/mcp)'
    required: false
    default: ''
  configurations:
    description: 'JSON array of test configurations for multiple transports. Each object: name, transport, start_command, server_url, env_vars'
    required: false
    default: ''

  # Test configuration
  compare_ref:
    description: 'Git ref to compare against (auto-detects merge-base or previous tag if not set)'
    required: false
    default: ''
  env_vars:
    description: 'Environment variables (newline-separated KEY=VALUE pairs)'
    required: false
    default: ''
  server_timeout:
    description: 'Timeout in seconds to wait for server response'
    required: false
    default: '10'

outputs:
  status:
    description: 'Test status (passed, differences, or error)'
    value: ${{ steps.conformance.outputs.status }}
  report_path:
    description: 'Path to the conformance report'
    value: 'conformance-report/CONFORMANCE_REPORT.md'

runs:
  using: 'composite'
  steps:
    # Optional language setup
    - name: Set up Node.js
      if: inputs.setup_node == 'true'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node_version }}

    - name: Set up Python
      if: inputs.setup_python == 'true'
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python_version }}

    - name: Set up Go
      if: inputs.setup_go == 'true'
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ inputs.go_version || null }}
        go-version-file: ${{ inputs.go_version == '' && 'go.mod' || null }}

    - name: Set up Rust
      if: inputs.setup_rust == 'true'
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
      with:
        toolchain: ${{ inputs.rust_toolchain }}

    - name: Set up .NET
      if: inputs.setup_dotnet == 'true'
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Download conformance test script
      shell: bash
      run: |
        curl -sSL -o /tmp/mcp-conformance-test.sh \
          https://raw.githubusercontent.com/sammorrowdrums/mcp-conformance-action/${{ github.action_ref || 'main' }}/scripts/conformance-test.sh
        chmod +x /tmp/mcp-conformance-test.sh

    - name: Set environment variables
      if: inputs.env_vars != ''
      shell: bash
      run: |
        echo "${{ inputs.env_vars }}" >> $GITHUB_ENV

    - name: Run conformance test
      id: conformance
      shell: bash
      env:
        MCP_INSTALL_COMMAND: ${{ inputs.install_command }}
        MCP_BUILD_COMMAND: ${{ inputs.build_command }}
        MCP_START_COMMAND: ${{ inputs.start_command }}
        MCP_SERVER_TIMEOUT: ${{ inputs.server_timeout }}
        MCP_COMPARE_REF: ${{ inputs.compare_ref }}
        MCP_TRANSPORT: ${{ inputs.transport }}
        MCP_SERVER_URL: ${{ inputs.server_url }}
        MCP_CONFIGURATIONS: ${{ inputs.configurations }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        set +e
        /tmp/mcp-conformance-test.sh > conformance-summary.txt 2>&1
        exit_code=$?
        set -e
        
        cat conformance-summary.txt
        
        if [ $exit_code -ne 0 ]; then
          echo "status=error" >> $GITHUB_OUTPUT
          echo "::error::Conformance test script failed with exit code $exit_code"
          exit 1
        elif grep -q "RESULT: ALL TESTS PASSED" conformance-summary.txt; then
          echo "status=passed" >> $GITHUB_OUTPUT
        elif grep -q "ERROR\|FATAL\|Server failed" conformance-summary.txt; then
          echo "status=error" >> $GITHUB_OUTPUT
          echo "::error::Conformance test encountered errors"
          exit 1
        else
          echo "status=differences" >> $GITHUB_OUTPUT
        fi

    - name: Generate Job Summary
      shell: bash
      run: |
        echo "# MCP Server Conformance Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -n "${{ inputs.compare_ref }}" ]; then
          echo "Comparing against: \`${{ inputs.compare_ref }}\`" >> $GITHUB_STEP_SUMMARY
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "Comparing tag against previous tag (auto-detected)" >> $GITHUB_STEP_SUMMARY
        else
          echo "Comparing against merge-base with \`origin/main\`" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f conformance-report/CONFORMANCE_REPORT.md ]; then
          tail -n +5 conformance-report/CONFORMANCE_REPORT.md >> $GITHUB_STEP_SUMMARY
        else
          echo "Report file not found - check the workflow logs for errors" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.conformance.outputs.status }}" = "passed" ]; then
          echo "**All conformance tests passed** - No behavioral differences detected." >> $GITHUB_STEP_SUMMARY
        else
          echo "**Differences detected** - Review the diffs above to ensure changes are intentional." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Common expected differences:" >> $GITHUB_STEP_SUMMARY
          echo "- New tools added" >> $GITHUB_STEP_SUMMARY
          echo "- Tool descriptions updated" >> $GITHUB_STEP_SUMMARY
          echo "- New resources or prompts" >> $GITHUB_STEP_SUMMARY
          echo "- Capability changes" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload conformance report
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: conformance-report
        path: conformance-report/
        if-no-files-found: ignore
